version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - npm test
    build:
        commands:
            - npm run webpack
artifacts:
    files:
        - index.html
        - favicon.ico
        - ColinJenkinsResume.pdf
        - styles/main.css
        - images/example1.png
        - images/example2.png
        - images/example3.png
        - dist/bundle.js
        - js/main.js
        - js/example-work.js
        - js/example-work-modal.js
